apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    orgId: 1
    isDefault: false
    editable: true
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: "1"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    orgId: 1
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET

