### POST request to create a userDetails
POST http://localhost:8072/accounts/api/users/create
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Test User",
  "password": "password123"
}

### GET request to fetch a userDetails by email address
GET http://localhost:8072/accounts/api/users/userDetails?aEmailAddress=test@example.com

### PUT request to update a userDetails
PUT http://localhost:8072/accounts/api/users/update
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Updated User",
  "password": "newpassword123"
}

### DELETE request to delete a userDetails by identifier
DELETE http://localhost:8072/accounts/api/users/delete?aIdentifier=test@example.com