services:

  # Keycloak

  keycloak:
    extends:
      file: common-microservices-config.yml
      service: keycloak
    depends_on:
      keycloakdb:
        condition: service_healthy
  # Api Gateway

  api-gateway:
    extends:
      file: common-microservices-config.yml
      service: api-gateway
    depends_on:
      servicediscovery:
        condition: service_healthy
      accounts:
        condition: service_healthy
      communities:
        condition: service_healthy

  # Service Discovery

  servicediscovery:
    extends:
      file: common-microservices-config.yml
      service: servicediscovery
    depends_on:
      configserver:
        condition: service_healthy

  # Config Server

  configserver:
    extends:
      file: common-microservices-config.yml
      service: configserver
    depends_on:
      keycloak:
        condition: service_healthy

  # ====================================================================================================================

  # Databases

  accountsdb:
    extends:
      file: db-config.yml
      service: accountsdb

  communitiesdb:
    extends:
      file: db-config.yml
      service: communitiesdb

  keycloakdb:
    extends:
      file: db-config.yml
      service: keycloakdb

      # ====================================================================================================================

      # Microservices

      # Accounts

  accounts:
    extends:
      file: microservices-config.yml
      service: accounts
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      servicediscovery:
        condition: service_healthy
      tempo:
        condition: service_started

      # Communities

  communities:
    extends:
      file: microservices-config.yml
      service: communities
    depends_on:
      configserver:
        condition: service_healthy
      communitiesdb:
        condition: service_healthy
      servicediscovery:
        condition: service_healthy
      tempo:
        condition: service_started

  # ====================================================================================================================

  # Observability

  # Loki

  loki:
    extends:
      file: observability-config.yml
      service: loki

  # Promtail

  promtail:
    extends:
      file: observability-config.yml
      service: promtail

  # Grafana

  grafana:
    extends:
      file: observability-config.yml
      service: grafana

  # Prometheus

  prometheus:
    extends:
      file: observability-config.yml
      service: prometheus

  # Tempo

  tempo:
    extends:
      file: observability-config.yml
      service: tempo

  # ====================================================================================================================

# Networks

networks:
  goaleaf_net:
    driver: "bridge"