services:

  # Accounts

  accounts:
    image: "com.goaleaf/glf-accounts:${ACCOUNTS_SERVICE_VERSION}"
    container_name: "glf-accounts"
    #    ports:
    #      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      OTP_SERVICE_NAME: "accounts"
      SPRING_DATASOURCE_URL: ${ACCOUNTS_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNTS_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNTS_SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${ACCOUNTS_SPRING_JPA_DATABASE_PLATFORM}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${ACCOUNTS_SPRING_JPA_DATASOURCE_DRIVERCLASSNAME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${ACCOUNTS_SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: ${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      COM_GOALEAF_ACCOUNTS_AUTH_SERVICE_URL: ${COM_GOALEAF_ACCOUNTS_AUTH_SERVICE_URL}
      COM_GOALEAF_ACCOUNTS_KEYCLOAK_REALM_NAME: ${COM_GOALEAF_ACCOUNTS_KEYCLOAK_REALM_NAME}
      COM_GOALEAF_ACCOUNTS_KEYCLOAK_CLIENTID: ${COM_GOALEAF_ACCOUNTS_KEYCLOAK_CLIENTID}
      COM_GOALEAF_ACCOUNTS_KEYCLOAK_CLIENTSECRET: ${COM_GOALEAF_ACCOUNTS_KEYCLOAK_CLIENTSECRET}
      COM_GOALEAF_ACCOUNTS_KEYCLOAK_GRANTTYPE: ${COM_GOALEAF_ACCOUNTS_KEYCLOAK_GRANTTYPE}
      COM_GOALEAF_ACCOUNTS_KEYCLOAK_SCOPE: ${COM_GOALEAF_ACCOUNTS_KEYCLOAK_SCOPE}
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readinessState | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

    # Communities

  communities:
    image: "com.goaleaf/glf-communities:${COMMUNITIES_SERVICE_VERSION}"
    container_name: "glf-communities"
    #    ports:
    #      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "communities"
      OTEL_SERVICE_NAME: "communities"
      SPRING_DATASOURCE_URL: ${COMMUNITIES_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${COMMUNITIES_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${COMMUNITIES_SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${COMMUNITIES_SPRING_JPA_DATABASE_PLATFORM}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${COMMUNITIES_SPRING_JPA_DATASOURCE_DRIVERCLASSNAME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${COMMUNITIES_SPRING_JPA_HIBERNATE_DDL_AUTO}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readinessState | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config